version: "3.7"

services:
  api:
    image: ys2lee/stable-diffusion-api:${TAG:-latest}
    build:
      context: .
      dockerfile: docker/api/Dockerfile

    restart: unless-stopped
    ports:
      - 3000:3000
    expose:
      - 3000
    volumes:
      - /home/USERNAME/.cache/huggingface:/root/.cache/huggingface
      - ./static:/app/static
    environment:
      TZ: Asia/Seoul
      MB_BATCH_SIZE: 1
      CUDA_DEVICE: cuda
      HUGGINGFACE_TOKEN: ${TOKEN:-YOUR-HUGGINGFACE-ACCESS-TOKEN}
      IMAGESERVER_URL: http://localhost:3000/images
      MB_TIMEOUT: 120
      SAVE_DIR: static

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]

  frontend:
    depends_on:
      - api

    image: ys2lee/stable-diffusion-streamlit:${TAG:-latest}
    build:
      context: ./frontend
      dockerfile: ../docker/frontend/Dockerfile

    restart: unless-stopped
    ports:
      - 8501:8501
    expose:
      - 8501
    environment:
      TZ: Asia/Seoul
      API_URL: http://api:3000
      ST_TITLE: Stable-diffusion
      ST_WIDE: "True"

  rabbitmq:
    restart: always
    build:
      context: .
      dockerfile: docker/remmitmq/Dockerfile
    ports:
      - "127.0.0.1:5672:5672"
      - "0.0.0.0:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"

  redis:
    restart: always
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    ports:
      - "6379:6379"

  redisinsights:
    image: redislabs/redisinsight:latest
    restart: always
    ports:
      - '8001:8001'
